# Generated by Django 4.1 on 2022-08-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processManager', '0002_alter_process_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Started'), ('F', 'Finished')], default='P', max_length=1),
        ),
    ]
